#' Export an author list with affiliations from the GFBI database
#'
#' @param data        Data frame used in the analysis. Must contain a `gfb3_dsn`
#'                    column — unique values are used to filter contributors.
#' @param data_sheet  Path to data_mastersheet.csv
#' @param contributor Path to contributor_mastersheet.csv
#' @param links       Path to links.csv (gfb3_dsn <-> contributor_id bridge)
#' @param format      One of "latex", "word", "text"
#' @param outfile     Output path without extension (extension added automatically)
#' @param title       Optional paper title used as heading in word/text output
#' @param sort_by     One of "last_name" (default) or "dataset" (order of first
#'                    appearance in data)
#'
#' @return Invisibly returns the deduplicated author data frame.
#'
#' @examples
#' export_author_list(
#'   data        = my_analysis_df,
#'   data_sheet  = "data_mastersheet.csv",
#'   contributor = "contributor_mastersheet.csv",
#'   links       = "links.csv",
#'   format      = "latex",
#'   outfile     = "authors"
#' )

export_author_list <- function(data,
                               data_sheet,
                               contributor,
                               links,
                               format   = c("latex", "word", "text"),
                               outfile  = "author_list",
                               title    = NULL,
                               sort_by  = c("last_name", "dataset")) {

  format  <- match.arg(format)
  sort_by <- match.arg(sort_by)

  # ── 1. Validate inputs ──────────────────────────────────────────────────────

  if (!"gfb3_dsn" %in% names(data)) {
    stop("'data' must contain a 'gfb3_dsn' column.")
  }

  for (f in c(data_sheet, contributor, links)) {
    if (!file.exists(f)) stop("File not found: ", f)
  }

  dsn_used <- unique(data$gfb3_dsn)
  dsn_used <- dsn_used[!is.na(dsn_used)]

  if (length(dsn_used) == 0L) {
    stop("No non-NA values found in data$gfb3_dsn.")
  }

  message("Extracting authors for ", length(dsn_used), " dataset(s)...")

  # ── 2. Query via DuckDB (connection managed internally) ─────────────────────

  con <- duckdb::dbConnect(duckdb::duckdb())
  on.exit(duckdb::dbDisconnect(con, shutdown = TRUE), add = TRUE)

  duckdb::duckdb_register(con, "data_sheet",  read.csv(data_sheet))
  duckdb::duckdb_register(con, "contributor", read.csv(contributor))
  duckdb::duckdb_register(con, "links",       read.csv(links))

  authors <- dplyr::tbl(con, "links") |>
    dplyr::filter(gfb3_dsn %in% dsn_used) |>
    dplyr::left_join(dplyr::tbl(con, "contributor"), by = "contributor_id") |>
    dplyr::collect()

  if (nrow(authors) == 0L) {
    stop("No contributors found for the gfb3_dsn values in 'data'.")
  }

  # ── 3. Sort and deduplicate ─────────────────────────────────────────────────

  if (sort_by == "dataset") {
    dsn_order <- match(authors$gfb3_dsn, dsn_used)
    authors   <- authors[order(dsn_order), ]
  }

  authors <- authors[!duplicated(authors$contributor_id), ]

  if (sort_by == "last_name") {
    authors <- dplyr::arrange(authors, last_name, first_name)
  }

  # ── 4. Build affiliation index ──────────────────────────────────────────────

  affil_cols <- c("affiliation_1", "affiliation_2", "affiliation_3")
  affil_cols <- affil_cols[affil_cols %in% names(authors)]

  all_affils <- authors |>
    dplyr::select(dplyr::any_of(affil_cols)) |>
    unlist(use.names = FALSE) |>
    (\(x) x[!is.na(x) & nchar(trimws(x)) > 0])() |>
    unique()

  affil_index <- stats::setNames(seq_along(all_affils), all_affils)

  authors$sup_nums <- lapply(seq_len(nrow(authors)), \(i) {
    affils <- unlist(authors[i, affil_cols], use.names = FALSE)
    affils <- affils[!is.na(affils) & nchar(trimws(affils)) > 0]
    as.integer(affil_index[affils])
  })

  # ── 5. Write output ─────────────────────────────────────────────────────────

  switch(format,
         latex = .write_latex(authors, all_affils, outfile, title),
         word  = .write_word( authors, all_affils, outfile, title),
         text  = .write_text( authors, all_affils, outfile, title)
  )

  out_path <- paste0(outfile, switch(format,
                                     latex = ".tex", word = ".docx", text = ".txt"))
  message("Written: ", out_path)

  invisible(authors)
}


# ── Internal helpers ──────────────────────────────────────────────────────────

.sup_str <- function(nums) paste(nums, collapse = ",")


.write_latex <- function(authors, all_affils, outfile, title) {

  lines <- c(
    "% Author list generated by export_author_list()",
    "% Requires: \\usepackage{authblk} or compatible package",
    ""
  )

  if (!is.null(title)) {
    lines <- c(lines, paste0("\\title{", title, "}"), "")
  }

  author_parts <- vapply(seq_len(nrow(authors)), \(i) {
    row <- authors[i, ]
    paste0(row$full_name, "$^{", .sup_str(row$sup_nums[[1]]), "}$")
  }, character(1))

  affil_lines <- vapply(seq_along(all_affils), \(i) {
    paste0("  $^{", i, "}$ ", all_affils[i])
  }, character(1))

  lines <- c(lines,
             "\\author{",
             paste(author_parts, collapse = ",\n"),
             "}",
             "",
             "\\affil{",
             affil_lines,
             "}"
  )

  writeLines(lines, con = paste0(outfile, ".tex"))
}


.write_text <- function(authors, all_affils, outfile, title) {

  lines <- character(0)

  if (!is.null(title)) {
    lines <- c(lines, title, strrep("-", nchar(title)), "")
  }

  author_parts <- vapply(seq_len(nrow(authors)), \(i) {
    row <- authors[i, ]
    paste0(row$full_name, " [", .sup_str(row$sup_nums[[1]]), "]")
  }, character(1))

  lines <- c(lines,
             paste(author_parts, collapse = ", "),
             "",
             "Affiliations:",
             vapply(seq_along(all_affils), \(i)
                    paste0("[", i, "]  ", all_affils[i]), character(1))
  )

  writeLines(lines, con = paste0(outfile, ".txt"))
}


.write_word <- function(authors, all_affils, outfile, title) {

  if (!requireNamespace("officer", quietly = TRUE)) {
    stop("Package 'officer' is required for Word output.\n",
         "Install with: install.packages('officer')")
  }

  doc <- officer::read_docx()

  if (!is.null(title)) {
    doc <- officer::body_add_par(doc, title, style = "heading 1")
  }

  doc <- officer::body_add_par(doc, "", style = "Normal")

  for (i in seq_len(nrow(authors))) {
    row <- authors[i, ]
    sup <- .sup_str(row$sup_nums[[1]])
    sep <- if (i < nrow(authors)) ", " else ""

    doc <- officer::body_add_run(doc,
                                 officer::ftext(row$full_name, officer::fp_text(font.size = 11))
    )
    doc <- officer::body_add_run(doc,
                                 officer::ftext(sup, officer::fp_text(font.size = 7,
                                                                      vertical.align = "superscript"))
    )
    if (nchar(sep) > 0) {
      doc <- officer::body_add_run(doc,
                                   officer::ftext(sep, officer::fp_text(font.size = 11))
      )
    }
  }

  doc <- officer::body_add_par(doc, "", style = "Normal")
  doc <- officer::body_add_par(doc, "Affiliations", style = "heading 2")

  for (i in seq_along(all_affils)) {
    doc <- officer::body_add_par(doc,
                                 paste0(i, "  ", all_affils[i]),
                                 style = "Normal"
    )
  }

  print(doc, target = paste0(outfile, ".docx"))
}
